<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="4" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-05T16:23:46 IST" name="Default suite" finished-at="2022-12-05T16:24:18 IST" duration-ms="32342">
    <groups>
    </groups>
    <test started-at="2022-12-05T16:23:46 IST" name="Default test" finished-at="2022-12-05T16:24:18 IST" duration-ms="32342">
      <class name="com.dinamic.v3.test.tescases.OrdersTestCase">
        <test-method is-config="true" signature="browserConfiguration()[pri:0, instance:com.dinamic.v3.test.tescases.OrdersTestCase@bae7dc0]" started-at="2022-12-05T16:23:46 IST" name="browserConfiguration" finished-at="2022-12-05T16:23:50 IST" duration-ms="4341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserConfiguration -->
        <test-method signature="log()[pri:0, instance:com.dinamic.v3.test.tescases.OrdersTestCase@bae7dc0]" started-at="2022-12-05T16:23:50 IST" name="log" finished-at="2022-12-05T16:23:51 IST" duration-ms="532" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- log -->
        <test-method signature="ordersEntry()[pri:1, instance:com.dinamic.v3.test.tescases.OrdersTestCase@bae7dc0]" started-at="2022-12-05T16:23:51 IST" name="ordersEntry" finished-at="2022-12-05T16:24:18 IST" duration-ms="26834" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ordersEntry -->
        <test-method signature="withoutItemDiscountPrice()[pri:2, instance:com.dinamic.v3.test.tescases.OrdersTestCase@bae7dc0]" started-at="2022-12-05T16:24:18 IST" name="withoutItemDiscountPrice" finished-at="2022-12-05T16:24:18 IST" duration-ms="143" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [26191] but found [2619]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [26191] but found [2619]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.dinamic.v3.test.pages.OMSPage.orderCalculation(OMSPage.java:212)
at com.dinamic.v3.test.tescases.OrdersTestCase.withoutItemDiscountPrice(OrdersTestCase.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withoutItemDiscountPrice -->
        <test-method is-config="true" signature="close()[pri:0, instance:com.dinamic.v3.test.tescases.OrdersTestCase@bae7dc0]" started-at="2022-12-05T16:24:18 IST" name="close" finished-at="2022-12-05T16:24:18 IST" duration-ms="425" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- com.dinamic.v3.test.tescases.OrdersTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
